{% set environment = 'prod' %}
-
  name: my-network-{{environment}}
  description: my network deployment for {{environment}} environment
  project: sourced-gus-1
  imports:
    - path: templates/network/network.py
  resources:
    - type: templates/network/network.py
      name: my-network-{{environment}}
      properties:
        autoCreateSubnetworks: false
-
  name: my-firewall-{{environment}}
  description: My firewall deployment for {{environment}} environment
  project: sourced-gus-1
  imports:
    - path: templates/firewall/firewall.py
  resources:
    - type: templates/firewall/firewall.py
      name: my-firewall-{{environment}}
      properties:
        network: !DMOutput dm://sourced-gus-1/my-network-{{environment}}/name
#        ox: !DMOutput dm://sourced-gus-1/my-network-{{environment}}/output/networkUrl
        rules:
          - name: allow-proxy-from-inside
            allowed:
              - IPProtocol: tcp
                ports:
                  - "80"
                  - "443"
            description: This rule allows connectivity to the HTTP proxies
            direction: INGRESS
            sourceRanges:
              - 10.0.0.0/8
          - name: allow-dns-from-inside
            allowed:
              - IPProtocol: udp
                ports:
                  - "53"
              - IPProtocol: tcp
                ports:
                  - "53"
            description: this rule allows DNS queries to google's 8.8.8.8
            direction: EGRESS
            destinationRanges:
              - 8.8.8.8/32

       #network: $(ref.my-project/my-network-{{environment}}:my-network-{{environment}}.name)
        # network: $(out.my-project/my-network-{{environment}}:name)

