{% set environment = 'prod' %}
name: my-network-{{environment}}
description: my network deployment for {{environment}} environment
project: sourced-gus-1
imports:
  - path: templates/network/network.py
resources:
  - type: templates/network/network.py
    name: my-network-{{environment}}
    properties:
      autoCreateSubnetworks: false
  - type: templates/network/network.py
    name: my-network-dev
    properties:
      autoCreateSubnetworks: false

