# Example on how to use the project template
#
# In this example, a project is created, along with some of the most used
# resources that an enterprise needs for regular operation
#
# Notice that the `parent.type` property defaults to "organization" so it
# doesn't need to be specified in the config. It is specified here for
# informational purposes
#
# See `templates/project.py.schema` for detailed information on these
# properties
#
# Replace the `parent.id` placeholder value with your organization ID.
# Replace the `billingAccountId` placeholder value with your billing
# account ID

imports:
  - path: templates/project/project.py
    name: project.py

resources:
  - name: test-project
    type: project.py
    properties:
      parent:
        type: organization
        id: 12345678901234567890
      billingAccountId: 111111-222222-333333
      activateApis:
        - compute.googleapis.com
        - deploymentmanager.googleapis.com
        - pubsub.googleapis.com
      serviceAccounts:
        - accountId: test-sa-1
          displayName: test service account 1
          roles:
            - roles/editor
            - roles/viewer
          networkAccess: true
      usageExportBucket: true
      sharedVPC: test-vpc-host-project
      sharedVPCSubnets:
        - subnetId: subnet-1
          region: us-east1
