# Example of the runtime config template usage.
#
# Replace the following placeholders with appropriate values:
#   <FIXME:config_name>: a config name unique within the project
#   <FIXME:waiter_name>: a waiter name unique within the project
# See https://cloud.google.com/deployment-manager/runtime-configurator/reference/rest/
# for details.

imports:
  - path: templates/runtime_config/runtime_config.py
    name: runtime_config.py

resources:
  - name: <FIXME:config_name>
    type: runtime_config.py
    properties:
      config: <FIXME:config_name>
      description: my config description
      variables:
        - variable: myapp/dev/sql/connection_string
          text: super text value
        - variable: myapp/dev/web/wildcardcert
          value: c3VwZXJhd2Vzb21ldGV4dAo=
      waiters:
        - waiter: <FIXME:waiter_name>
          timeout: 3.5s
          success:
            cardinality:
              path: myapp/dev
              number: 2
