name: sourced-cft-demo-0
project: {{env.CFT_PROJECT_ID}}
imports:
  - path: templates/project/project.py
    name: project.py
resources:
  - name: sourced-cft-demo-0
    type: project.py
    properties:
      parent:
        type: folder
        id: {{env.CFT_ORGANIZATION_FOLDER_ID}}
      billingAccountId: {{env.CFT_BILLING_ACCOUNT_ID}}
      activateApis:
        - compute.googleapis.com
        - deploymentmanager.googleapis.com
        - pubsub.googleapis.com
        - container.googleapis.com
      serviceAccounts:
        - accountId: cft-demo-sa-0
          displayName: cft demo service account 0
          roles:
            - roles/editor
            - roles/viewer
          networkAccess: true
      usageExportBucket: false
